### ISSUE TITLE
使 http://g0v.tw/ 成為 g0v 的入口網頁而非顯示g0v.tw 中央政府總預算

### ISSUE THREAD

**Issue by hychen** [g0v/dev#1]
將 g0v.tw  中央政府總預算 改成 g0v.tw 的一個sub site, 而 g0.vtw 則改為g0v的入口網頁。
在g0v.tw 首頁做好前，只需留個連結引導至 dev.g0v.tw 即可。

**Comment by ETBlue** [comment]
註：前幾天 Mindos Chen 在 Facebook 上找了 Even Wu 做 g0v.tw 首頁設計，Even 說 ok 但要到 2 月才會有空，然後記得 2 月時要提醒他一下。（如果 2 月來不及的話也許得問問看有沒有其他 designer 目前有空）

**Comment by audreyt** [comment]
我問了一下，Isis Kang 說願意幫忙設計，不過手上也有案子在趕，所以可能也要 1 月底 / 2 月初才會做出雛型。

**Comment by hychen** [comment]
首頁設計的todo 開在 https://github.com/g0v/dev/issues/2

**Comment by clkao** [comment]
g0v.tw is now gh-pages of github.com/g0v/g0v.tw
