### ISSUE TITLE
backup hackpad

### ISSUE THREAD

**Issue by kcwu** [g0v/dev#11]
現在 g0v 太多東西放 hackpad, 除了 hackpad 自己的 history 功能, 應該另外作備份

需要技能
- 會寫程式抓網頁資料

可能作法
- 寫個設定檔要備份 *.hackpad.com 哪幾個 project
- hackpad 有提供 api, 透過 api 找出要備份的文章並抓下來
- 每天自動抓, 並 commit 到 github 上(把 github 當作儲存空間)

**Comment by ETBlue** [comment]
有可能被份 https://g0v.hackpad.com/ 裡面所有的 hackpad 嗎？前幾天把目前看到的文件都移到 g0v 這個 instance 底下了（可能還有些比較早期的落在 hackpad.com 底下）

**Comment by clkao** [comment]
有個簡單的作法： hackpad 有 sync to dropbox 的功能。所以可以註冊一個專門的 account，sync 到他 server 上的 dropbox, 然後定期 snapshot 進 github

**Comment by kcwu** [comment]
目前發現 hackpad api 抓到的資料中文會壞掉.
report bug here: https://hackpad.com/Hackpad-API-bugs-xVJvm6lxNL1

**Comment by kcwu** [comment]
script https://github.com/kcwu/hackpad-backup
backup repo here https://github.com/kcwu/hackpad-data-g0v

**Comment by jessy1092** [comment]
!!!!!!  晚了一步... 被做完了   

我測試了 clkao 的方法   然後寫了batch file 來定時同步到 github 

但最後發現  Hackpad Sync to dropbox 好像不會自動Sync to dropbox  只能自己手動  = =...
