### ISSUE TITLE
g0v.tw 首頁設計

### ISSUE THREAD

**Issue by hychen** [g0v/dev#2]
首頁提供下列資訊
- g0v 是什麼
  - 理念 (clkao provides a draft)
  - 運作方式 (clkao provides a draft)
- 怎麼加入(連結到 dev.g0v.tw)
  -專案成果列表(連結到各專案首頁)
  - e.x: g0v.tw 中央預算

目的是讓任何人可以在3個click內找到他要的資訊

**Comment by ETBlue** [comment]
簡單弄了 g0v.tw 網站的概念草圖，在設計師有空動工前大家可以先討論收集靈感，這樣進度會比較快 XD

首頁： https://docs.google.com/drawings/d/1bMNfThR4_Zex6Q-Fcbd8iVESPfttmR0g4th7C05ULnw/edit
專案列表頁： https://docs.google.com/drawings/d/1m_4IJ9Vwv0sdXyRQzuMXbEUlKO3NNpRFIidjQuxOqqU/edit
活動列表頁： https://docs.google.com/drawings/d/1ZRob2HkWMAjXhwqCtEQw6jf5pTBKkh_UmvgktvglqV4/edit
如何加入g0v： https://docs.google.com/drawings/d/1UqSJry0aORKdO9rjWKE-Xm4WwQn9gFvM5bru8lBT1WI/edit

以上權限設定是anyone can edit請自由修改 XD

**Comment by walkingice** [comment]
上次提到的想法，其實沒有很複雜，主要是想把東西整合起來，協助新進者找到方向

http://0xlab.org/~walkingice/g0v.png

**Comment by bobchao** [comment]
![Photo 13-1-27 10 38 53](https://f.cloud.github.com/assets/168931/100577/ab9dd3de-682b-11e2-9808-8d2190a24d61.png) 我大概針對訪客需要的資訊及需要的元素先列了列。

**Comment by bobchao** [comment]
我把兩位的 mockups 看一遍，其實沒有很大差別
不過 @walkingice 在單一專案的顯示部份，似乎希望專案直接「嵌」在 g0v.tw 裡 (with iframe maybe)，
我會建議做個公用的 title bar 以 JavaScript 讓大眾直接引入即可，
我們不需直接嵌進來，這樣會大家在安排版面會自由得多。

參考 https://developer.mozilla.org/zh-TW/demos/detail/seam-carving-for-javascript/launch 最上面那條

如果還沒有人要實作我就先放著了...

**Comment by ETBlue** [comment]
bobchao: 立院公報的圖檔人肉 OCR 專案需要一般人的參與！希望 g0v.tw 官網能規劃一區是讓任何人不需專業技術也可以透過這邊加入 g0v 的，然後把像是人肉 OCR 這類專案的協力介面放在那邊給人家來用~~~

**Comment by bobchao** [comment]
@ETBlue 我想其中一個很大的需求會是希望「這一區是獨特的，且顯眼」對嗎？亦及不與其他專案一起放？

或許可以是在「加入零時政府」直接說「如果你只有十分鐘可以幫忙，先幫忙 OCR 吧！」然後導人到專案頁裡 tag as crowdsourcing 的專案。

**Comment by bobchao** [comment]
我改了 ETBlue 的兩頁，如果大家覺得還不錯接下來我就繼續改別的，有什麼問題歡迎留 comment 在圖上討論比較直接

https://docs.google.com/drawings/d/1bMNfThR4_Zex6Q-Fcbd8iVESPfttmR0g4th7C05ULnw/edit
https://docs.google.com/drawings/d/1m_4IJ9Vwv0sdXyRQzuMXbEUlKO3NNpRFIidjQuxOqqU/edit

**Comment by ETBlue** [comment]
目前似乎只有OCR這個專案是需要大量一般人參加的，在首頁幫我們promote當然是很好啦 XDXD 不過將來要是有其他專案也有類似的需求的話，跟別的同樣需要一般人參與的專案放在同一區也是可以的。至於要放在g0v.tw內部還是獨立的專案頁面，目前還沒想法... 都可？XD

hackpad好像有個「我會什麼->我可以做什麼」的頁面，不曉得 g0v.tw 網站裡面有沒有這樣的地方，讓使用者依照自己目前有的專長，選擇要加入什麼專案，這樣的話，人肉OCR就可以放在「我認識字->我可以加入g0v」的頁面裡... XD

**Comment by walkingice** [comment]
我原本的想法是在 g0v.tw 的網頁寫下各專案的基本介紹，再加上到 github 的連結。對 g0v 有興趣的 programmer 進來網頁之後，能夠從列表找出自己可能感興趣的專案來參與。

考量到會有不少非 programmer 的人，獨立出顯眼的一區並且輔助他們參與是很棒的想法。

目前是先用 jekyll 產生出靜態的網頁來顯示資訊(https://github.com/g0v/g0v.tw/commits/gh-pages)，優點是不會寫網頁的人(像我就是 :P)，也能夠用 markdown 的語法產生頁面，資訊補足之後就能夠先有一個暫時堪用的頁面。

我想要先產生基本的頁面，再朝著兩位的意見慢慢改進。看起來 bob + etblue 的想法，用 jekyll 有點難達成。有建議的工具組合能做到嗎？我可能要重新學起 (當然有熟稔的高人出手是很歡迎的啦 XD)

**Comment by clkao** [comment]
最近的討論與 flow / structure 在： http://hack.g0v.tw/meta/YC0Ig73WEMJ

**Comment by clkao** [comment]
本輪設計暫告一段落。
