### ISSUE TITLE
新成員手冊

### ISSUE THREAD

**Issue by hychen** [g0v/dev#3]
新成員手冊之目的為提供所有想參與幫忙的人一個快速適應g0v的工作(玩樂?)模式
等等任何可以幫助新成員的資訊。 草稿在[這](http://lqfb-test.g0v.tw/lf/initiative/show/8.html)

**Comment by ttcat** [comment]
oops! 我新加入，本想看一下草稿，但得到了：404 - Not Found

**Comment by audreyt** [comment]
試試看這份？ https://hackpad.com/--ZYU6qiYaQLo

**Comment by ttcat** [comment]
got it! Thanks!

On Sat, May 18, 2013 at 8:38 PM, 唐鳳 notifications@github.com wrote:

> 試試看這份？ https://hackpad.com/--ZYU6qiYaQLo
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/g0v/dev/issues/3#issuecomment-18100318
> .

## 

吳銘軒

專案統籌 | 綠色公民行動聯盟
FB : http://www.facebook.com/gcaa.org.tw
+886 935 697 573

**Comment by ETBlue** [comment]
對了，誰熟悉哪個專業領域該在這個 hackpad 中登記嗎？還是去歷屆黑客松的鄉民列表裡面找？例如 ttcat 對網路連署平台熟悉，公督盟的朋友對立院運作熟悉，我跟 pofeng 對醫療領域熟悉之類的～

**Comment by clkao** [comment]
http://g0v.tw/join.html should be good enough for this now.
