### ISSUE TITLE
g0v 宣言 or 運作方式

### ISSUE THREAD

**Issue by hychen** [g0v/dev#4]
當組織越來越大後可能會發生一些問題，g0v現在雖小，但似乎成長越來越快，所以要有些
簡單的規範以應對下列問題
- 參與g0v的人對某些議題有爭議發生時如何處理
- g0v對媒體的處理方式
- g0v對贊助的處理方式
- 產出物的授權方式

**Comment by ipaaa** [comment]
我會先擬個宣言草稿出來以利討論

**Comment by clkao** [comment]
current draft: https://github.com/g0v/dev/wiki/g0v-manifesto-(draft)

**Comment by clkao** [comment]
http://g0v.tw/manifesto.html
