### ISSUE TITLE
setup  liquid feedback

### ISSUE THREAD

**Issue by hychen** [g0v/dev#6]
see http://liquidfeedback.org/
- aslo doing deb package and juju charm.

**Comment by clkao** [comment]
didn't notice there's already chef recipe for this:
https://github.com/computerlyrik/chef-liquid-feedback
will try with that later.

**Comment by clkao** [comment]
a test instance is now available at http://ec2-54-245-156-253.us-west-2.compute.amazonaws.com/lf
